const $=s=>document.querySelector(s);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chapters=['Alert','Meld investigates','Responder joins','Share evidence','Mitigate','Verify'];
const human='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5"/><path d="M5 21v-3a7 7 0 0 1 14 0v3"/></svg>';
const evidence={traces:'Datadog · checkout-api · production\n02:00–02:02\n18.4% errors · p95 2.8 s\nConnectionAcquireTimeout\nNo checkout deployment in this window.',sessions:'Terminal 1 · Maya · database read scope\n02:04 · pg_stat_activity\n\nreconciliation-worker 82\ncheckout-api           9\nother                  4\n\nConfigured maximum: 100\nSession counts alone do not establish causation.',diff:'GitHub · worker configuration\nDeployed 01:58\n\n- concurrency: 8\n+ concurrency: 80\n\nCheckout errors begin at 02:00.\nCorroborated by database session ownership.',recovery:'Fresh window: 02:07–02:09, after rollback\n324 checkout requests\nError rate 0.3% (required <1%)\np95 240 ms (required <500 ms)\nConnections 24/100 and falling\n\nIllustrative scenario, not live telemetry.'};
// One ordered timeline drives the room, work ledger, terminals and all views.
const beats=[
{c:0,d:3000,caption:'A checkout alert opens one shared incident.',alert:true,task:'Opening incident'},
{c:1,d:3200,caption:'Meld checks traces and changes before the team joins.',room:['Meld','Checkout requests are timing out while waiting for database connections. I found a worker change at 01:58; session ownership is still unverified.'],tool:['Datadog','Query error traces','done'],ref:'traces',task:'Comparing worker configuration'},
{c:2,d:3300,caption:'Maya joins briefed and checks database sessions with her own access.',join:'Maya',view:'personal',personal:['Maya’s assistant','The worker holds 82 of 100 connections. I’ll attach the session output so the room can assess it.'],taskMaya:'Inspecting database sessions',terminal:true,output:true},
{c:3,d:3300,caption:'Maya publishes a sourced finding; Meld follows the new lead.',publish:true,view:'room',room:['Maya','The reconciliation worker holds 82 of 100 connections. Please correlate this with the 01:58 change.'],ref:'sessions',taskMaya:'Session evidence shared'},
{c:4,d:3500,caption:'The team reviews a targeted rollback through its existing workflow.',join:'Jordan',view:'jordan',brief:true,review:true,approved:true,deployed:true,jordan:['Jordan’s assistant','The worker concurrency changed from 8 to 80. Jordan reviewed the rollback to 8 through the deployment workflow.'],taskJordan:'Running approved workflow'},
{c:5,d:3600,caption:'Meld waits for fresh traffic before marking recovery verified.',view:'room',sample:2,recovered:true,room:['Meld','Fresh checks: 324 requests across two minutes, 0.3% errors, p95 240 ms, and connections falling to 24/100. Recovery verified.'],ref:'recovery',task:'Recovery verified',taskJordan:'Recovery checked',end:true}
];
let index=0,elapsed=0,playing=false,clock=null,last=0,override=null;
let state;
const stage=$('#story-stage');
function build(n){const s={room:[],personal:[],jordan:[],tools:{},people:[],activity:[],view:'room',task:'Waiting for alert',taskMaya:'',taskJordan:'',sample:0};for(let i=0;i<=n;i++){const b=beats[i];if(b.view)s.view=b.view;for(const k of ['task','taskMaya','taskJordan','sample'])if(b[k]!==undefined)s[k]=b[k];for(const k of ['terminal','output','selection','finding','publish','brief','change','review','approved','deployed','recovered','end'])if(b[k])s[k]=true;for(const k of ['room','personal','jordan'])if(b[k])s[k].push({who:b[k][0],text:b[k][1],ref:b.ref,i});if(b.tool){s.tools[b.tool[1]]={source:b.tool[0],name:b.tool[1],status:b.tool[2]};s.activity.push({name:'Meld',text:b.tool[1]+' · '+b.tool[2]});}if(b.extraTool){s.tools[b.extraTool[1]]={source:b.extraTool[0],name:b.extraTool[1],status:b.extraTool[2]};}if(b.join){s.people.push(b.join);s.activity.push({name:b.join,text:'Joined the incident'});}if(b.publish)s.activity.push({name:'Maya',text:'Shared database session evidence'});if(b.taskJordan)s.activity.push({name:'Jordan',text:b.taskJordan});}return s;}
const brandSlugs={Datadog:'datadog',GitHub:'github',AWS:'amazonaws',Postgres:'postgresql'};
const brandIcon=name=>brandSlugs[name]?`<img class="provider-glyph" src="assets/brands/${brandSlugs[name]}.svg" alt="">`:'';
const avatar=who=>{const ai=who.includes('assistant')||who==='Meld';const person=who.includes('Jordan')?'jordan':'maya';return `<span class="avatar ${ai?'ai meld-agent':`human-avatar ${person}`}" aria-label="${esc(who)}">${ai?'<img src="meldhq-mark.svg?v=identity-6" alt="">':person==='jordan'?'JO':'MA'}</span>`;};
const source=key=>`<button class="source-link" data-evidence="${key}">${brandIcon(key==='traces'?'Datadog':key==='diff'?'GitHub':'')}<span>${({traces:'Datadog · traces',sessions:'Terminal 1 · lines 12–18',diff:'GitHub · configuration diff',recovery:'Recovery · fresh checks'})[key]} ↗</span></button>`;
const messages=items=>items.map(m=>`<article class="story-message ${m.i===index?'new-message':''}">${avatar(m.who)}<div><div class="message-meta"><strong>${esc(m.who)}</strong><time>${m.i<2?'02:02':m.i<4?'02:04':m.i<5?'02:06':'02:09'}</time></div><p>${esc(m.text)}</p>${m.ref?source(m.ref):''}</div></article>`).join('');
const task=(name,text)=>text?`<div class="work-item"><strong class="work-owner">${avatar(name.split(" + ")[0])}${esc(name)}</strong><span>${esc(text)}</span><small>${text.includes('verified')||text.includes('shared')||text.includes('checked')?'✓ Complete':'● In progress'}</small></div>`:'';
function terminal(){return `<section class="live-terminal"><header><span>⌘ Terminal 1 · Maya</span><small>Database · read</small></header><div class="terminal-body"><div class="prompt"><span>maya@commerce ~ % </span><span id="typed-terminal">${state.output?esc("psql commerce -c 'SELECT application_name, count(*) FROM pg_stat_activity GROUP BY 1;'"):''}</span>${!state.output?'<b class="typing-caret">▍</b>':''}</div>${state.output?`<pre class="terminal-output ${state.selection?'selected-output':''}"><span>12  application_name         count</span><span>13  ──────────────────────────────</span><span>14  reconciliation-worker      82</span><span>15  checkout-api                9</span><span>16  other                       4</span><span>17  (3 rows)</span><span>18  observed 02:04</span></pre><div class="terminal-footer">${state.selection?'Lines 12–18 selected':'Query completed · 0.18s'} <button data-action="prepare">${state.selection?'Prepare finding ↗':'Select evidence'}</button></div>`:''}</div></section>`;}
function recovery(){return `<div class="recovery-live"><span class="rail-title">POST-CHANGE CHECKS · 02:07–02:09</span><h4>${state.recovered?'Recovery verified':'Collecting fresh traffic'}</h4><div class="recovery-grid"><div><strong>${state.recovered?'0.3%':'0%'}</strong><span>Errors · target &lt;1%</span></div><div><strong>${state.recovered?'240':'260'} ms</strong><span>p95 · target &lt;500 ms</span></div><div><strong>${state.recovered?'324':'23'}</strong><span>Requests · minimum 100</span></div><div><strong>${state.recovered?'24':'71'}/100</strong><span>Connections · falling</span></div></div><p>${state.recovered?'✓ Two-minute observation window passed':'Waiting · sample and time window insufficient'}</p></div>`;}
function review(){return `<div class="change-review"><span class="rail-title">DEPLOYMENT REVIEW · JORDAN</span><h4>Restore worker concurrency</h4><div class="change-diff"><span>worker.concurrency</span><del>80</del><strong>8</strong></div><p>Existing deployment workflow · production<br>Tradeoff: temporarily lower worker throughput.</p>${source('diff')}<button class="scene-action" data-action="approve" ${state.approved?'disabled':''}>${state.deployed?'✓ Deployment completed':state.approved?'✓ Approved · deploying…':'Approve simulated rollback'}</button></div>`;}
function body(view){if(view==='services')return `<div class="console-page"><span class="rail-title">SERVICES / OBSERVED RELATIONSHIPS</span><h3>Follow the affected path.</h3><div class="service-map"><div>checkout-api<small>Production · affected</small></div><span>→</span><div>commerce-db<small>Connection pressure</small></div><span>←</span><div>reconciliation-worker<small>Changed 01:58</small></div></div><p>Mapped from Datadog traces, AWS runtime metadata, and the connected GitHub repository.</p>${source('traces')}${source('diff')}</div>`;
if(view==='connections')return `<div class="console-page"><span class="rail-title">CONNECTED TOOLS</span><h3>Context and access, ready to work.</h3>${[['Datadog','Logs, traces, metrics','Meld · read'],['GitHub','commerce repository','Meld · read'],['AWS','ECS runtime metadata','Meld · scoped role'],['Postgres','Database session inspection','Maya · read'],['Deployment workflow','Restore worker configuration','Jordan · review required']].map(x=>`<div class="connection-row"><strong>${brandIcon(x[0])}${x[0]}</strong><span>${x[1]}</span><small>${x[2]}</small></div>`).join('')}</div>`;
if(view==='activity')return `<div class="console-page"><span class="rail-title">TEAM ACTIVITY</span><h3>Parallel work. Shared direction.</h3>${state.activity.slice().reverse().map(x=>task(x.name,x.text)).join('')}</div>`;
if(view==='case')return `<div class="console-page"><span class="rail-title">CASE FILE</span><h3>The evidence behind the explanation.</h3><div class="hypothesis"><span>${index>=3?'SUPPORTED':'INVESTIGATING'}</span><strong>Checkout is waiting for database connections.</strong>${source('traces')}</div><div class="hypothesis"><span>${index>=4?'SUPPORTED':'INVESTIGATING'}</span><strong>The worker’s increased concurrency consumed the pool.</strong>${state.publish?source('sessions'):''}${index>=4?source('diff'):''}</div><div class="hypothesis"><span>${index>=4?'NOT OBSERVED IN WINDOW':'PENDING CHECK'}</span><strong>A checkout deployment caused the failures.</strong></div></div>`;
if(view==='tools')return `<div class="console-page"><span class="rail-title">MELD / TOOL ACTIVITY</span><h3>Every check is inspectable.</h3>${Object.values(state.tools).map(t=>`<div class="tool-run"><span>${t.status==='done'?'✓':'◌'}</span><div><strong>${brandIcon(t.source)}${t.source} · ${t.name}</strong><p>${t.status==='done'?'Completed':'Running…'}</p>${t.status==='done'?source(t.source==='GitHub'?'diff':'traces'):''}</div></div>`).join('')}</div>`;
if(view==='terminal')return terminal();
if(view==='personal')return `<div class="context-banner">Maya’s investigation <span>Room context attached · database read access</span></div>${messages(state.personal)}${state.terminal&&!state.finding?terminal():''}${state.finding&&!state.publish?`<div class="finding-preview"><span class="rail-title">REVIEW BEFORE SHARING</span><p id="typed-finding"></p>${source('sessions')}<button class="scene-action" data-action="share">Share finding with room ↗</button></div>`:''}`;
if(view==='jordan')return `<div class="context-banner">Jordan’s investigation <span>Deployment workflow access</span></div>${state.brief?'<div class="join-brief"><span class="rail-title">CAUGHT UP THROUGH 02:05</span><h4>Connection pressure is blocking checkout.</h4><p>Maya found 82 worker sessions. Meld is correlating the configuration change.</p><strong>Unclaimed: validate rollback and monitor recovery.</strong></div>':''}${messages(state.jordan)}${state.review?review():''}`;
return `${index===0?'<div class="incoming-alert"><span class="live-dot"></span>02:00 AM · Datadog page received<strong>Checkout error rate above threshold</strong><span>production · 18.4% errors</span></div>':''}${index>=1?`<div class="compact-brief"><span>${state.recovered?'RECOVERED':'IMPACT'}</span><strong>${state.recovered?'Checkout serving normally':'Checkout · 18.4% errors'}</strong><small>${state.publish?'Worker session evidence shared':'Connection owner not yet verified'}</small></div>`:''}${messages(state.room)}${state.join?'<div></div>':''}${state.sample?recovery():''}${state.end?`<a class="scene-action" href="${$('.booking').href}">Explore this with your team ↗</a>`:''}`;}
function render(){state=build(index);const view=override||state.view;const b=beats[index];stage.innerHTML=`<div class="console-shell animated-console"><nav class="console-nav" aria-label="Preview application"><b class="console-brand"><img src="meldhq-mark.svg?v=identity-6" alt=""><span>Meld<span>HQ</span></span></b><small>COMMERCE TEAM</small>${[['room','◉','Incidents'],['services','◇','Services'],['connections','⇄','Connections']].map(([v,icon,label])=>`<button data-view="${v}" class="${view===v?'active':''}">${icon} &nbsp; ${label}</button>`).join('')}<div class="console-user">${avatar(view==='jordan'?'Jordan':'Maya')}<strong>${view==='jordan'?'Jordan':'Maya'}</strong><small>On-call responder</small></div></nav><div class="room-shell"><div class="room-head"><div><span class="room-id">INC-042 / COMMERCE / PRODUCTION</span><h3>Checkout failures</h3></div><span class="badge ${state.recovered?'verified':''}">${state.recovered?'Recovery verified':state.deployed?'Verifying recovery':state.approved?'Deploying':'Investigating'}</span></div><div class="room-tabs">${[['room','Room'],['personal','My investigation'],['activity','Activity'],['case','Case file']].map(([v,n])=>`<button data-view="${v}" class="${view===v||(v==='personal'&&view==='jordan')?'selected':''}">${n}</button>`).join('')}<span class="room-participants">${['Meld',...state.people].map(p=>`<span class="participant">${avatar(p)}<span>${p}</span></span>`).join('')}</span></div><div class="room-work"><div class="scene-scroll" tabindex="0" aria-label="Investigation conversation"><div class="room-conversation">${body(view)}</div></div><aside class="work-card"><span class="rail-title">LIVE WORK</span>${task('Meld',state.task)}${task('Maya + assistant',state.taskMaya)}${task('Jordan + assistant',state.taskJordan)}<div class="tool-status-list">${Object.values(state.tools).map(t=>`<div><span class="${t.status==='running'?'live-dot':''}">${t.status==='done'?'✓':''}</span>${brandIcon(t.source)}${t.source}<small>${t.status==='done'?'Checked':'Running'}</small></div>`).join('')}</div></aside></div><div class="console-composer">${avatar(view==='jordan'?'Jordan':'Maya')}<span id="typed-composer">${b.type&&!b.target?'':'Ask, investigate, or share a finding…'}</span>${b.type&&!b.target?'<b class="typing-caret">▍</b>':''}<span class="send-icon">↑</span></div><div class="console-bottom"><button data-view="terminal">⌘ Terminal</button><button data-view="tools">Tool activity</button><span>${view==='jordan'?'Jordan · authorized workflow':view==='personal'?'Maya · database read':'Meld · telemetry, code, runtime'}</span></div></div></div>`;
$('#chapter-count').textContent=String(b.c+1).padStart(2,'0')+' / 06';$('#story-caption').textContent=b.caption;$('#previous').disabled=index===0;$('#next').disabled=index===beats.length-1;
$('.chapters').innerHTML=chapters.map((n,i)=>`<button data-chapter="${i}" aria-label="Chapter ${i+1}: ${n}" title="${n}" class="${i===b.c?'current':i<b.c?'complete':''}"><span>${String(i+1).padStart(2,'0')}</span><i></i></button>`).join('');
const scroll=$('.scene-scroll');if(view==='room'||view==='personal')scroll.scrollTop=scroll.scrollHeight;sync();typeFrame();}
function sync(){$('#play').textContent=playing?'Pause':'Play';$('#play').setAttribute('aria-label',playing?'Pause walkthrough':'Play walkthrough');$('#watch').textContent=playing?'Pause walkthrough':'Play the walkthrough';$('#play-state').textContent=playing?'Playing · '+chapters[beats[index].c]:'Paused · explore the console';}
function typeFrame(){const b=beats[index];if(b.type&&!override){const el=$('#typed-'+(b.target||'composer'));if(el){const fraction=!playing||matchMedia('(prefers-reduced-motion: reduce)').matches?1:Math.min(1,elapsed/(b.d*.76));el.textContent=b.type.slice(0,Math.floor(b.type.length*fraction));}}const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const message=$('.new-message p');if(message&&!override){const original=(b.room||b.personal||b.jordan)?.[1];if(original)message.textContent=original.slice(0,!playing||reduced?original.length:Math.ceil(original.length*Math.min(1,elapsed/(b.d*.60))));}if(b.output&&!override){document.querySelectorAll('.terminal-output>span').forEach((line,i)=>line.style.visibility=!playing||reduced||elapsed>(i*200)?'visible':'hidden');}const bar=$('.chapters .current i');if(bar)bar.style.width=Math.min(100,elapsed/beats[index].d*100)+'%';}
function pause(){playing=false;clearInterval(clock);clock=null;sync();}
function jump(n,manual=true){if(manual)pause();index=Math.max(0,Math.min(beats.length-1,n));elapsed=0;override=null;render();}
function start(){if(index===beats.length-1)jump(0);if(override){override=null;render();}playing=true;last=performance.now();sync();clearInterval(clock);clock=setInterval(()=>{const now=performance.now();elapsed+=Math.min(now-last,500);last=now;typeFrame();if(elapsed>=beats[index].d){if(index===beats.length-1){pause();return;}jump(index+1,false);}},40);}
$('#play').onclick=()=>playing?pause():start();$('#watch').onclick=()=>{if(playing)pause();else{$('#workspace').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});start();}};
$('#restart').onclick=()=>jump(0);$('#next').onclick=()=>jump(index+1);$('#previous').onclick=()=>jump(index-1);$('.chapters').onclick=e=>{const b=e.target.closest('[data-chapter]');if(b)jump(beats.findIndex(x=>x.c===Number(b.dataset.chapter)));};
stage.onclick=e=>{const v=e.target.closest('[data-view]');if(v){pause();override=v.dataset.view;render();return;}const a=e.target.closest('[data-action]');if(a){jump(a.dataset.action==='prepare'?3:a.dataset.action==='share'?3:5);return;}const ref=e.target.closest('[data-evidence]');if(ref){pause();$('#evidence-content').textContent=evidence[ref.dataset.evidence];$('#evidence-dialog').showModal();}};
stage.addEventListener('wheel',()=>{if(playing)pause();},{passive:true});stage.addEventListener('keydown',e=>{if(['ArrowUp','PageUp','PageDown'].includes(e.key)&&playing)pause();});$('#close-evidence').onclick=()=>$('#evidence-dialog').close();$('#evidence-dialog').onclick=e=>{if(e.target===$('#evidence-dialog'))e.target.close();};render();

$('#expand-story').onclick=()=>{const p=$('.story-product');const wide=p.classList.toggle('theater');$('#expand-story').textContent=wide?'Close expanded view':'Expand console ↗';$('#expand-story').setAttribute('aria-expanded',String(wide));};document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('.story-product').classList.remove('theater');$('#expand-story').textContent='Expand console ↗';$('#expand-story').setAttribute('aria-expanded','false');}});
// Source context converges into Meld, then becomes evidence in the room.
const flow=$('#meld-flow'),flowControl=$('#flow-motion'),flowCanvas=$('.flow-canvas'),flowSvg=$('.flow-wires');
const flowReduced=matchMedia('(prefers-reduced-motion: reduce)');
let flowPaused=flowReduced.matches,flowVisible=false,flowTime=0,flowLast=0,flowFrame=0,flowPaths=[],flowPackets=[],outPath,outPacket,lastEvidence=-1;
const ns='http://www.w3.org/2000/svg';
const makeSvg=(tag,attrs)=>{const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n;};
const flowSources=[['datadog','traces'],['github','change'],['amazonaws','runtime'],['backstage','owner']];
function layoutFlow(){const r=flowCanvas.getBoundingClientRect(),core=$('.meld-core').getBoundingClientRect(),room=$('.flow-room').getBoundingClientRect();if(!r.width)return;flowSvg.setAttribute('viewBox',`0 0 ${r.width} ${r.height}`);const paths=$('#ingest-paths'),packets=$('#ingest-packets');paths.replaceChildren();packets.replaceChildren();flowPaths=[];flowPackets=[];const mobile=r.width<600,cx=core.left-r.left+core.width/2,cy=core.top-r.top+core.height/2;
 document.querySelectorAll('.flow-source').forEach((el,i)=>{const a=el.getBoundingClientRect(),sx=mobile?a.left-r.left+a.width/2:a.right-r.left,sy=mobile?a.bottom-r.top:a.top-r.top+a.height/2;const d=mobile?`M${sx},${sy} C${sx},${sy+40} ${cx},${cy-65} ${cx},${cy}`:`M${sx},${sy} C${sx+65},${sy} ${cx-75},${cy} ${cx},${cy}`;const path=makeSvg('path',{d,class:'context-path'});paths.append(path);flowPaths.push(path);const g=makeSvg('g',{class:'context-packet'});g.append(makeSvg('rect',{x:-19,y:-19,width:38,height:38,rx:10}));g.append(makeSvg('image',{href:`assets/brands/${flowSources[i][0]}.svg`,x:-10,y:-10,width:20,height:20}));packets.append(g);flowPackets.push(g);});
 const ex=mobile?room.left-r.left+room.width/2:room.left-r.left,ey=mobile?room.top-r.top:room.top-r.top+room.height/2;outPath=makeSvg('path',{d:mobile?`M${cx},${cy} C${cx},${cy+70} ${ex},${ey-35} ${ex},${ey}`:`M${cx},${cy} C${cx+80},${cy} ${ex-70},${ey} ${ex},${ey}`,class:'context-path context-output'});paths.append(outPath);outPacket=makeSvg('g',{class:'context-packet evidence-packet'});outPacket.append(makeSvg('rect',{x:-28,y:-13,width:56,height:26,rx:6}));const text=makeSvg('text',{'text-anchor':'middle',y:4});text.textContent='linked';outPacket.append(text);packets.append(outPacket);drawFlow();}
const limit=n=>Math.max(0,Math.min(1,n));
function drawFlow(){const t=flowTime%12000,roundNow=Math.floor(flowTime/12000);let ingesting=false;flowPackets.forEach((g,i)=>{const icons=document.querySelectorAll(`.flow-source[data-source="${i}"] .provider img`);if(icons.length)g.querySelector('image').setAttribute('href',icons[roundNow%icons.length].getAttribute('src'));});flowPackets.forEach((g,i)=>{const p=limit((t-500-i*350)/3600),e=p*p;const pt=flowPaths[i].getPointAtLength(flowPaths[i].getTotalLength()*e);const scale=1-.92*Math.pow(p,5);g.setAttribute('transform',`translate(${pt.x} ${pt.y}) scale(${scale})`);g.style.opacity=flowReduced.matches?'0':String(p===0||p===1?0:Math.min(1,p*10,(1-p)*14));if(p>.83&&p<1)ingesting=true;});if(outPath){const p=limit((t-5750)/2100),pt=outPath.getPointAtLength(outPath.getTotalLength()*p);outPacket.setAttribute('transform',`translate(${pt.x} ${pt.y})`);outPacket.style.opacity=flowReduced.matches?'0':String(p===0||p===1?0:Math.min(1,p*8,(1-p)*10));}flow.classList.toggle('absorbing',ingesting);const phase=t<1500?0:t<5700?1:t<7900?2:3;flow.dataset.phase=phase;$('#flow-caption').textContent=['Your sources. Connected to the investigation.','Meld brings signals, changes, resources, and ownership together.','Context becomes linked evidence—not another disconnected feed.','The team starts with a shared picture and tools to act.'][phase];if(phase===3||flowReduced.matches){const round=Math.floor(flowTime/12000);if(round!==lastEvidence){lastEvidence=round;$('#ingested-text').textContent=['Worker deployment linked to checkout timeouts','Database pressure linked to worker concurrency','Service owner and rollback path identified'][round%3];}}}
function tickFlow(now){flowFrame=0;if(flowPaused||!flowVisible||document.hidden)return;if(flowLast)flowTime+=Math.min(now-flowLast,100);flowLast=now;drawFlow();flowFrame=requestAnimationFrame(tickFlow);}
function syncFlow(){flow.classList.toggle('flow-paused',flowPaused);flowControl.textContent=flowPaused?'Play animation':'Pause animation';flowControl.setAttribute('aria-pressed',String(flowPaused));cancelAnimationFrame(flowFrame);flowFrame=0;flowLast=0;if(!flowPaused&&flowVisible&&!document.hidden)flowFrame=requestAnimationFrame(tickFlow);}
flowControl.onclick=()=>{flowPaused=!flowPaused;syncFlow();};flowReduced.addEventListener('change',e=>{flowPaused=e.matches;layoutFlow();syncFlow();});document.addEventListener('visibilitychange',syncFlow);
new ResizeObserver(layoutFlow).observe(flowCanvas);new IntersectionObserver(entries=>{flowVisible=entries[0].isIntersecting;syncFlow();},{threshold:.12}).observe(flow);layoutFlow();syncFlow();

// Public early-access intake. The API accepts only an email; approval is handled in MeldHQ.
{
 const form=document.getElementById('early-access-form');
 const status=document.getElementById('access-status');
 if(form)form.addEventListener('submit',async event=>{
  event.preventDefault();
  const button=form.querySelector('button[type=submit]');
  const email=form.elements.email.value.trim();
  status.classList.remove('error');status.textContent='Sending your request…';button.disabled=true;
  try{
   const response=await fetch('https://app.meldhq.net/api/early-access',{
    method:'POST',headers:{'Content-Type':'application/json'},
    body:JSON.stringify({email,website:form.elements.website.value})
   });
   if(!response.ok){const result=await response.json().catch(()=>({}));throw Error(result.detail||'Please try again in a moment.');}
   form.reset();status.textContent='Request received. We’ll review it and reach out by email.';
  }catch(error){status.classList.add('error');status.textContent=error.message||'Could not submit your request. Please try again.';}
  finally{button.disabled=false;}
 });
}
